name: docker
 
on:
  push:
    branches: [ main ]
 
jobs:
  verify:
    runs-on: ubuntu-latest
 
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - name: Build Docker image
      run: | 
        docker build \
        -t ${{ secrets.DOCKER_USER }}/homeworklinux:build-${{ github.sha }} \
        -t ${{ secrets.DOCKER_USER }}/homeworklinux:latest \
        -f docker/Dockerfile \
        docker/
 
        echo "Docker image built successfully"
        docker images | grep ${{ secrets.DOCKER_USER }}/homeworklinux
 
    - name: Save Docker image
      run: docker save -o /tmp/docker-image.tar ${{ secrets.DOCKER_USER }}/homeworklinux:build-${{ github.sha }}
      
    - name: Upload Docker image
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: /tmp/docker-image.tar
 
  test:
    runs-on: ubuntu-latest
    needs: verify
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s
 
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp
 
      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar
 
      - name: Run tests
        run: |
          docker run --network host \
            -e TESTING=1 \
            ${{ secrets.DOCKER_USER }}/homeworklinux:build-${{ github.sha }} pytest -v ./tests/
 
  deploy:
    runs-on: self-hosted
    needs: [ test ]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/tasks/docker
            ./restart.sh
